### ISSUE TITLE
Build issue with autoconf

### ISSUE THREAD

**Issue by jtdaugherty** [judah/terminfo#49] opened 2022-11-20 02:38 UTC
I'm having a bit of trouble building `terminfo` (245be5c4755d34cbf2c21c3a4865efbb5d72a6ec). Am I missing something?

Tools:
```
cabal-install version 3.8.1.0
compiled using version 3.8.1.0 of the Cabal library

The Glorious Glasgow Haskell Compilation System, version 9.4.2
```
The behavior:
```
$ cabal new-build
Resolving dependencies...
Build profile: -w ghc-9.4.2 -O1
In order, the following will be built (use -v for more details):
 - terminfo-0.4.1.5 (lib:terminfo) (first run)
Configuring terminfo-0.4.1.5...
Warning: The 'build-type' is 'Configure' but there is no 'configure' script.
You probably need to run 'autoreconf -i' to generate it.
Error: cabal-3.8.1.0: configure script not found.
```

**Comment by jtdaugherty** [comment] 2022-11-20 02:41
I was able to get a working build by taking the above advice and running `autoreconf -i`, but still, I imagine that's not what you expect to happen.

**Comment by judah** [comment] 2022-11-20 03:29
It looks like this is intended behavior of Cabal:
https://github.com/haskell/cabal/issues/4903#issuecomment-346548919

The configure script is generated from the `configure.ac` file and is included in source distributions to Hackage, but intentionally not checked into the git repo.

It could be worth mentioning this in the repo README; would you like to send a patch?

**Comment by jtdaugherty** [comment] 2022-11-20 03:34
I am happy to submit a patch to add an extra instruction to the README, but I guess I'm confused now about why `configure` would be included in the Hackage sdist. Wouldn't that possibly be wrong for some target systems? Wouldn't it be best to *always* generate a `configure` on the target system as part of the build process?

**Comment by jtdaugherty** [comment] 2022-11-20 03:38
(Also, thanks for investigating that.)

**Closed** 2022-11-20 15:56 UTC
