### ISSUE TITLE
ncurses/curses is not listed as dependency

### ISSUE THREAD

**Issue by fmthoma** [judah/terminfo#15] opened 2016-05-28 11:25 UTC
Although `(n)curses.h` is obviously a dependency, it is not listed in the cabal file. This might be the reason why stack/nix builds break for [some people](https://github.com/commercialhaskell/stack/issues/1584) including me.

This can be resolved by adding

``` yaml
nix:
  packages: [ncurses]
```

in the `stack.yaml` of projects using `terminfo`.

However, I would assume that a

```
pkgconfig-depends: ncurses
```

(or `libncurses`?) in your `terminfo.cabal` would just solve this problem for everyone.

**Comment by judah** [comment] 2016-05-28 15:19
Thanks for the suggestion.  The problem is that the relevant library is available by different names in different systems.  On some it's `ncurses`, for some it's `curses`, some it's `tinfo`, etc...for an example of how tricky this is, see: https://ghc.haskell.org/trac/ghc/ticket/7281

Currently we solve this issue using `Build-type: Configure` in the .cabal file (and then checking which library is installed in the `configure` script.  Is there a way for stack/nix to run the ./configure script in order to figure out which package to use?

**Comment by fmthoma** [comment] 2016-05-30 19:39
Okay, point taken :-)

Unfortunately, NixOS won't even provide the `ncurses` dependency unless it is explicitly listed, which is why the build script fails. On the other hand, since the name of the library is [stable in NixOS](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/ncurses/default.nix), there won't be any guessing necessary.

I guess adding a `default.nix` file in the project root will do the trick for this specific case. I will have a look into it and maybe come up with a pull request one of the next days.

**Comment by fmthoma** [comment] 2016-06-05 11:57
FYI: https://github.com/NixOS/nixpkgs/issues/15995

**Comment by judah** [comment] 2018-07-27 06:06
Closing since it looks like the nixpkgs ghc now provides ncurses automatically.

**Closed by judah** 2018-07-27 06:06 UTC
